apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyc-service
  labels:
    app:  kyc-backend
spec: 
  replicas: 2
  selector:
    matchLabels:
      app:  kyc-backend
  template:
    metadata:
      labels:
        app:  kyc-backend
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command:
          - "/bin/sh"
          - "-c"
          - "/usr/local/bin/wait-for-it 63.23.230.13:5432 --timeout=60 --strict -- echo 'PostgreSQL is up'"
      containers:
        - name: kyc-service
          image: cecillwala/kyc-kyc-service
          ports:
            - containerPort: 8081

---
            
apiVersion: v1
kind: Service
metadata:
  name: kyc-service
spec:
  type: ClusterIP
  selector:
    app: kyc-service
  ports:
    - port: 8081
      targetPort: 8081
