apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: report-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: giktekkyc.org
    http:
      paths:
      - path: /report(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: report-frontend
            port: 
              number: 80
