apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . 8.8.8.8 67.207.67.3 67.207.67.2
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2025-06-12T08:36:51Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "220"
  uid: fd274e40-faea-4e9c-b665-12038bf67a2a
