name: dockerize

on: 
  push:   
    branches: ["opened"]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: cecillwala
        password: Xarelto@123
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: cecillwala/k8s-backend:latest
