apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_CONNECTION: jdbc:postgresql://postgres:5432/kyc_db
  POSTGRES_DB: kyc_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres