apiVersion: v1
kind: Secret
metadata:
  name: kyc-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXMK
  POSTGRES_PASSWORD: cG9zdGdyZXMK
  CLUSTER_NAME: a3ViZXJuZXRlcwo=
  CONTEXT_NAME: a3ViZXJuZXRlcy1hZG1pbkBrdWJlcm5ldGVzCg==
  RABBITMQ_USER:  Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
  